# Generated by Django 2.2.7 on 2019-12-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='address',
            field=models.CharField(default='Ghaziabad - Meerut Highway, NH-58, Ghaziabad, Uttar Pradesh 201206, India', max_length=1000),
        ),
    ]
